theme: minima
title: Glenn S. Ritchey III
description: The academic and creative works. Maintained by <a href="https://github.com/gr9430">gr9430</a>.
header_pages: []
url: "http://glennritchey.com"
baseurl: ""